version: "3.6"
services:
  certi:
    image: techblog/certi
    container_name: certi
    restart: always
    environment:
      - API_KEY=
      - SLEEP_TIME=
      - NOTIFIERS=
      - LOG_LEVEL= 
    restart: unless-stopped
    volumes:
      - ./data:/opt/certi/db