version: "3.6"
services:
  certi:
    image: techblog/certi
    container_name: certi
    restart: always
    environment:
      - API_KEY= # Certspotter API key
      - DB_USER= #DB USER
      - DB_PASS= #DB Password
      - DB_HOST= #DB Host
      - DB_NAME= #DB Name
      - DB_PORT=3306 # MySQL Port
      - SLEEP_TIME= #[Sleep between searches - Default is 3600 seconds])
      - NOTIFIERS= #[Apprise notifiers]
    restart: unless-stopped